### ISSUE TITLE
Serial Connection Issue with Connect/Disconnect button

### ISSUE THREAD

**Issue by dunaden001** [CartesianCo/argentum-control#16]
The Connect/Disconnect button seems to have issues actually releasing the com port (tested in Win 7).  Additionally the COM port list doesn't seem to refresh except on start up - should update whenever expanded.

**Comment by dunaden001** [comment]
Just as some further explanation by example, if you connect to the Arduino and then remove the USB cable without Disconnecting.  The software will allow you to disconnect but _not_ to reconnect.

http://forum.cartesianco.com/threads/connection-problem-with-arc-software-and-arduino.598/

**Comment by trent-waddington** [comment]
The second part of this (port list automatically updating) has been fixed. I think this fixes the first part too, but some more testing would be good. I've experienced the port-goes-away-while-connected problem and I don't like that you have to manually press Disconnect.
