### ISSUE TITLE
Print should home before commencing then move back to where it was positioned.

### ISSUE THREAD

**Issue by dunaden001** [CartesianCo/argentum-control#17]
After reset, the firmware will assume the printer is at (0,0).  Instead it should assume that it is calibrated, not make any assumptions on position and only stop movement if it engages a limit switch.  Instead of homing the carriage _after_ every print layer, this should occur _before_ every print layer.  This way the printer always knows it's position before printing a layer.

**Comment by dunaden001** [comment]
note: further explanation on this in #28

**Comment by trent-waddington** [comment]
Resolved by Print View.
