### ISSUE TITLE
Soft stop events should prompt user & possibly be replaced with only hard stops

### ISSUE THREAD

**Issue by dunaden001** [CartesianCo/argentum-control#18]
In the event that the printer is commanded to move past what it believes to be the bounds of the print area, it simply skips this command and continues otherwise as normal.  By default, this really should prompt the user otherwise it appears as if everything is working correctly.  When coupled with the printer assuming it's position to be (0,0) on reset without homing before a layer - it's very likely for a user to accidentally perform an entire layer without any x-axis movement.

In this way, if a print moves past the print area boundary, the user can choose what to do with the print but there is no case where blindly continuing printing while missing commands will produce a useful or positive result.

Additionally, there are limit switches based at each axis extremity which makes live soft stops redundant (ie. the firmware does not need to monitor soft stops - only the software).  The software should definitely warn the user if it believes a layer will expand past the print area boundaries but this is only necessary as pre-analysis.  In this way, a limit switch will only be triggered in these cases:
- the printer is calibrating - the firmware responds to the software and the software sends the next commands appropriately.
- the printer is homing - the firmware responds (or simply stops and waits) and the software can now safely assume which commands would cause the limit switch to be triggered and warns the user beforehand.
- the printer is printing a layer and has lost it's position by skipping or being moved manually - this triggers the print to pause and wait for user input on a prompt in the software.  The software also updates its assumption on carriage position.

NOTE: if the user directly inputs a movement command to the arrow buttons or terminal that would engage a limit switch (not a command within a print layer) - the software could either truncate the movement to prevent engaging the switch or simply let the switch engage and then update its assumption on carriage position.

**Comment by trent-waddington** [comment]
Resolved by Print View.
