### ISSUE TITLE
X/Y axes are reversed 

### ISSUE THREAD

**Issue by trent-waddington** [CartesianCo/argentum-control#27]
Press the "up" arrow on the gui and you will see M X 150 appears in the output. Similarly, "left" results in M Y -200. The home position (the bottom left corner of the print area) should be X=0, Y=0 and with X increasing left to right and Y increasing bottom to top.

**Comment by dhylands** [comment]
Yes - I will be much happier when this gets fixed.
I finally had to put some tape on my printer to keep the axis straight in my head since they were reversed from everything else I have (3D pritner, CNC mill).

**Comment by trent-waddington** [comment]
This is fixed on the develop branch. You'll need both firmware and GUI updates.

**Comment by trent-waddington** [comment]
I actually got printing to work now and it doesn't rotate or flip the image anymore.
