### ISSUE TITLE
stest should have configurable time length

### ISSUE THREAD

**Issue by dunaden001** [CartesianCo/argentum-control#39]
The command that is used to test the stepper motors ('stest') only runs for a few seconds and then stops.  This makes it impractical to use it while tuning the current limits on the stepper drivers.

Ideally the command would run for a specified amount of time with an option to run indefinitely.

Additionally the printer does not react to the limit switches while this command is running.  This means it's very easy to cause the printer to grind against an edge and skip continuously.  The ideal solution for this is to have the command begin with a homing sequence and then move to the centre of the print bed before executing the command.

One extra thought is that the command only tests the strength of the stepper motors at a very small range of positions.  Ideally the command would traverse the full space in some movement pattern to test the strength of the motors across all possible situations.

**Comment by trent-waddington** [comment]
So, like, does stest exist or what? I don't see any code in the firmware that implements it. Is it a script or something?

**Comment by dunaden001** [comment]
I think maybe at the time that I created this, I was running on a previous version before you took control from Michael.  I guess it probably existed as a script on the control software side, not the firmware.
I think the stest command should exist in some form or another if it doesn't currently (don't currently have a machine on which to test in Shenzhen).  But the ideal would be a command that goes to (0,0) then goes to hit the limit switches at (max_x, max_y), then hits the limit switch at (max_x, 0), then same at (0, max_y) and then back to (0,0).  This just tests all possible conditions for the stepper motors and lets users check to see if any cables or whatnot is catching.  Then you just set the command to run X number of times (or indefinitely) while you tune the steppers.

Hit me up if that doesn't make sense.

**Comment by trent-waddington** [comment]
Umm.. that just sounds like the calibrate command to me.

**Comment by dunaden001** [comment]
yeah, well we've actually been using the calibrate button to test assembled printers so far but it would be good to be able to run it indefinitely or run it faster (and presuming it's already calibrated, it can decelerate before slamming the switches perhaps).

**Comment by trent-waddington** [comment]
Okay, I added a Printer -> Utilities -> Stepper Motor Test action which will show a dialog and do the stest dance until you hit cancel.
