### ISSUE TITLE
Printer loses home position

### ISSUE THREAD

**Issue by trent-waddington** [CartesianCo/argentum-control#41]
If the computer connects to the printer when the print head is not in the home position, the printer seems to designate whatever position the head is in as the home position. Attempting to move the head using the GUI will not move back past the new home position. The only way to get out of this situation appears to be recalibration, which is a pain.

As I understand it, this is caused by the board resetting every time a connect occurs. I'm hesitant to remove this behavior (even if I knew how to do it) because I've used Disconnect/re-Connect to solve "head banging into the sides" problems during calibration and if I didn't have that I wouldn't know what to do. Regardless, this behavior forces the user to make sure the print head is in the home position before disconnecting - which is all well and good if the firmware took care of it, but it's sometimes not possible.

**Comment by arielbriner** [comment]
Resetting on connect is hard wired into the arduino. We can physically change the behavior, but I agree that it's not the best plan. 

I think the solution is for the printer to store its print area size and motor orientation from the last calibration (which I assume it already does) and use that information to just move towards the home corner until it detects the limit switches. It can even record the steps traveled and move back to where it started if we want. I guess this is 'homing'.

**Comment by dunaden001** [comment]
This issue is also directly addressed in #18 for the issue of not being able to move left on start-up and #17 / #28 address the issue of defining where the home position is with arbitrary initial position before a layer.

**Comment by trent-waddington** [comment]
On develop the home key now goes to x-min/y-min limits.
