### ISSUE TITLE
Serial terminal doesn't clear after sending command

### ISSUE THREAD

**Issue by dunaden001** [CartesianCo/argentum-control#43]
It would be very useful if the text input widget for typing commands to be sent to the printer cleared after sending the command.

ie. I type 'pwm 8 254' into the terminal line and hit Enter.  The software sends the command and then clears the terminal line and retains focus ready for me to type a new command without any further action.

**Comment by CartesianCo** [comment]
Trent already fixed that. :)

**Comment by dhylands** [comment]
It would also be realy nice if you could use the up/down arrow key to go though previous commands.

**Comment by trent-waddington** [comment]
Also already fixed on develop. :)
