### ISSUE TITLE
AVRDude doesn't work on Mac

### ISSUE THREAD

**Issue by johnscott4** [CartesianCo/argentum-control#44]
It seems that the avrdude executable is not shipping +x on Mac. Also, the python code to invoke it doesn't seem to use ./avrdude or -C avrdude,config. Otherwise it seems to work, as long as no-one has the tty port open.

**Comment by trent-waddington** [comment]
Added what I think is a fix, but I haven't tested it.

**Comment by trent-waddington** [comment]
Okay, I think this is fixed.
