### ISSUE TITLE
Comms error recognized as outdated firmware

### ISSUE THREAD

**Issue by dunaden001** [CartesianCo/argentum-control#47]
A communications error between printer and software will be identified as an outdated firmware type.  There should be an unchanging validation character set (ie. "Firmware version:") and if this set is not received, the machine will not prompt to update firmware.

It could then just alert the user or perform some action to ensure the port is configured correctly.

This issue was encountered by a Linux user that found he had to configure his port to operate at 115200 BAUD before communications would work:
http://forum.cartesianco.com/threads/error-upgrading-firmware.626/#post-927

**Comment by trent-waddington** [comment]
The firmware check issue is already fixed. I'll try to reproduce the issue with the baud rate.
