### ISSUE TITLE
Servo calibration menu should be disabled until drying actually available.

### ISSUE THREAD

**Issue by robwalks** [CartesianCo/argentum-control#50]
It's simply a one line change in the UI and should be done to avoid confusion until the feature is truly available.

From forums.
Kenneth Lim
http://forum.cartesianco.com/threads/feedback-210115.744/

**Comment by trent-waddington** [comment]
Okay done. Can you open a new issue with a list of what needs to be done to make this feature "truly available"? It's certainly not clear to me.
