### ISSUE TITLE
The STOP button should seriously stop the machine like an emergency stop concept.

### ISSUE THREAD

**Issue by robwalks** [CartesianCo/argentum-control#52]
When i used it for the first time and did not calibrate with the motors moving in the reverse direction, the machine continually jammed and unpowering should have resolved the issue. However, unplugging the USB cable did that and STOP button failed on me.

From forums.
Kenneth Lim
http://forum.cartesianco.com/threads/feedback-210115.744/

**Comment by trent-waddington** [comment]
Emergency stop, done.
