### ISSUE TITLE
The "motor flipped" configuration should be saved in a local config file

### ISSUE THREAD

**Issue by robwalks** [CartesianCo/argentum-control#53]
The "motor flipped" configuration should be saved in a local config file instead of having the user to manually "calibrate" each time in order for the Application to know that's the setting.

From forums.
Kenneth Lim
http://forum.cartesianco.com/threads/feedback-210115.744/

**Comment by trent-waddington** [comment]
Actually, it should be saved on the printer.. and is.. now.
