### ISSUE TITLE
Printer starts resumes calibration after being shut off and then powered back on

### ISSUE THREAD

**Issue by mkohler99** [CartesianCo/argentum-control#62]
If the printer is running a calibration and I power it off, the calibration appears to be running in ARC still because when I power it back up (for instance, after performing some work on a loose pulley in the back of the machine) and reconnect, the printer continues running its calibration. I dont think the machine should ever start moving on its own after it has been powered up because there is no way for it to know what state it is in. This usually results in the machine slamming into the endstop, making an angry clicking noise, and me having to shut it off again, manually killing the calibration job, and then powering the machine up again, and reconnecting it. I think when the connection to the printer is lost, the calibration should abort.

**Comment by trent-waddington** [comment]
Indeed. I added lots of power checks. If the user turns off the power switch the printer will not move once the power is restored until a new command is initiated.
